baseURL = "https://nanpangyou.github.io/"
languageCode = "en-us"
title = '男胖友de部落格'
theme = "yinyang"
[author]
  name = "nanpangyou"
  homepage = "https://nanpangyou.github.io/"
[params]
 headTitle = "这里是男胖友" 
 mainSections = ["post"]
[[params.socials]]
name = "About Me"
[[params.socials]]
name = "Github"
link = "https://github.com/nanpangyou"